version: '3.8'

services:
  trackly:
    build: .
    volumes:
      - ${MUSIC_PATH:-./music}:/music:ro  # Read-only mount of music directory
      - ./config:/config  # Persistent storage for config files
    environment:
      - UPDATE_INTERVAL=00:00  # Default to midnight
      - DISCORD_WEBHOOK=  # Set this to your Discord webhook URL
      - DISCORD_ROLE=  # Set this to your Discord role ID to ping
    restart: unless-stopped
    container_name: trackly
    user: "${UID:-1000}:${GID:-1000}"  # Use host user's UID/GID for proper permissions