version: '3.8'

services:
  artist-tracker:
    build: .
    volumes:
      - ${MUSIC_PATH:-./music}:/music:ro  # Read-only mount of music directory
    environment:
      - MUSIC_PATH=/music
      - UPDATE_INTERVAL=${UPDATE_INTERVAL:-"00:00"}  # Default to midnight
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
    restart: unless-stopped
    container_name: artist-tracker