# docker-compose.yml
version: '3.8'

services:
  trackly:
    build: .
    volumes:
      - ${MUSIC_PATH:-./music}:/music:ro  # Read-only mount of music directory
      - ./config:/config  # Persistent storage for config
    environment:
      - UPDATE_INTERVAL=00:00  # Default to midnight
      - DISCORD_WEBHOOK=  # Set this to your Discord webhook URL
    restart: unless-stopped
    container_name: trackly